#!/bin/bash
# update and scan antivirus clam
clear
read -p "Нужно обновление антивируса? (Y/n) "

case $REPLY in
	y|"") echo "### Обновление антивируса"
	        sleep 3
		sudo freshclam
		echo "### проверка на вирусы"
		sleep 3
		sudo clamscan -ir --remove /home
		;;
	n)	echo "### проверка на вирусы"
		sleep 3
		sudo clamscan -ir --remove /home
		;;
	*)	exit
		;;
esac
